### ISSUE TITLE
Install type (Pkg vs App Store)

### ISSUE THREAD

**Issue by nixtar** [pbowden-msft/ExtensionAttributes#5]
Hello,

Sorry if this is not the right place to ask this kind of thing.
Is it possible to detect how an office app was installed ( AppStore or via PKG )?

Cheers,
Nick

**Comment by pbowden-msft** [comment]
Sorry for the slow reply. Yes - see https://github.com/pbowden-msft/ExtensionAttributes/blob/master/InstallSource_Outlook.sh for an example.
