### ISSUE TITLE
Need visibility on which volume license is being utilized

### ISSUE THREAD

**Issue by mpermann** [pbowden-msft/ExtensionAttributes#7]
Paul,
It would be great to have some visibility on which volume license type is installed when this condition is met. I'm in the process of rolling out the Office 2021 LTSC volume licensing installer and being able to report on which license file is there would be helpful. I had a much more rudimentary script that checked between for 2016 and 2019. When I added the check for `/usr/bin/grep -q "Bozo+MzVxzFzbIo+hhzTl4xkRZSjOUX8J8nIgpXuMa"` it wasn't reporting that I had 2021 license installed even though the About Word GUI showed I did. I ran the newer 2021 VL installer without removing the existing licensing file. For now, I am going to remove the existing licensing file before I install the 2021 file and hope that helps get me the reporting I need. Thanks!
Mike

https://github.com/pbowden-msft/ExtensionAttributes/blob/26ed6efe200d0a62889bf86cb8f1b8a325efae66/Office_License.sh#L153-L154

**Comment by pbowden-msft** [comment]
Thanks for the feedback! Fixed in the latest update.
